apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  namespace: istio-demo
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: gcr.io/cirrus-initial-project/customer:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: istio-demo
  labels:
    app: customer    
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: customer
  type: LoadBalancer